version: "3"

services:
  api:
    # build from Dockerfile
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "5000:5000"
    container_name: "megapod-api"
    volumes:
      - .:/usr/src/megapod
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_DEBUG=1
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@megapod-db:5432/megapod-dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@megapod-db:5432/megapod-test
    command: "python3 -m flask run -h 0.0.0.0"
    depends_on:
      - megapod-db
  
  megapod-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .data:/var/lib/postgresql/data
    container_name: megapod-db
    